[tool]
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "0.0.0"
version_files = [
    "include/esystest/config.h",
    "include/esystest/version.h",
    "scripts/conan_pkg_version.env",
    "conanfile.py:version",
]
