variables:
    TXT_E: "\e[31m"
    TXT_S: "\e[35m"
    TXT_W: "\e[33m"
    TXT_CLEAR: "\e[0m"

stages:
  - check
  - build

run_pre_commit:
  stage: check
  tags:
    - ubuntu20.04
  script:
    - scripts/pre_commit_test.sh

.create_conan_pkg: &create_conan_pkg
  stage: build
  script:
    - scripts/conan_configure.sh
    - scripts/conan_build_pkg.sh
    - scripts/conan_publish_gitlab.sh $ESYSTEST_CONAN_USER_CHANNEL
    - scripts/conan_publish_libesys.sh $LIBESYS_CONAN_USER $LIBESYS_CONAN_PASSWORD $ESYSTEST_CONAN_USER_CHANNEL
    - scripts/conan_publish_jfrogio.sh $LIBESYS_CONAN_USER $LIBESYS_CONAN_PASSWORD $ESYSTEST_CONAN_USER_CHANNEL
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^bump:/

create_conan_pkg_testing:ubuntu20_04:
  <<: *create_conan_pkg
  tags:
    - ubuntu20.04
  variables:
    ESYSTEST_CONAN_USER_CHANNEL: "@libesys/testing"
  except:
    - master

create_conan_pkg:ubuntu20_04:
  <<: *create_conan_pkg
  tags:
    - ubuntu20.04
  variables:
    ESYSTEST_CONAN_USER_CHANNEL: ""
  only:
    - master
